 'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ArrowUpRight,Search,MapPin,Check,Loader2,ChevronRight,BookOpen,Compass,RefreshCw,Eye,Utensils,Store,Globe2,X,Maximize2,Info} from 'lucide-react';
import {creatures,type Creature,type Route} from '@/lib/catalogue';
import {countries} from "@/lib/countries";
import Globe from './globe';
import {Specimen,Sprite} from './specimen';
import {TinyFishKeyButton,TinyFishKeyNotice,useTinyFishKey} from './tinyfish-key';
type Result={title:string;url:string;snippet:string;checked:boolean;mention:boolean;exactSpecies:boolean;excerpts:string[];token:string};
type Discovery={query:string;checkedAt:string;location:string;species:string;route:Route;endpoints:string[];warning:string;results:Result[]};
type AgentState={busy:boolean;progress:string;result?:Record<string,unknown>;error?:string};
const routeDetails={see:{title:'Find an aquarium',subtitle:'Search public aquariums and exhibits that name this creature.',scene:'aquarium',icon:Eye},eat:{title:'Find a restaurant',subtitle:'Search restaurant menus for this seafood.',scene:'restaurant',icon:Utensils},buy:{title:'Find a fishmonger',subtitle:'Search fishmongers and seafood shops for this ingredient.',scene:'fishmonger',icon:Store}};

export default function Detail({fish}:{fish:Creature}){
const {hasKey,revision,openKey,requestHeaders}=useTinyFishKey();
const [view,setView]=useState<'about'|Route>('about'),[aboutTab,setAboutTab]=useState<'overview'|'life'>('overview'),[cookTab,setCookTab]=useState<'shops'|'recipes'>('shops');
const [globeOpen,setGlobeOpen]=useState(false);
const [route,setRoute]=useState<Route>(fish.routes[0]||'see'),[location,setLocation]=useState('London'),[country,setCountry]=useState('GB');
const [busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[data,setData]=useState<Discovery|null>(null);
const [agents,setAgents]=useState<Record<string,AgentState>>({});const requestId=useRef(0);const keyRequests=useRef(new Set<AbortController>());const abort=useRef<AbortController|null>(null);
const [recipe,setRecipe]=useState<{title:string;url:string;snippet:string}[]>([]);const [recipeBusy,setRecipeBusy]=useState(false);const [recipeError,setRecipeError]=useState('');
useEffect(()=>()=>{abort.current?.abort();keyRequests.current.forEach(controller=>controller.abort());},[]);
useEffect(()=>{requestId.current++;abort.current?.abort();keyRequests.current.forEach(controller=>controller.abort());keyRequests.current.clear();setRecipeBusy(false);setBusy(false);setData(null);setAgents({});setRecipe([]);setError('');setRecipeError('');},[revision]);
useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape')setGlobeOpen(false);}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
function switchView(next:'about'|Route){requestId.current++;abort.current?.abort();setBusy(false);setError('');setView(next);if(next!=='about'){setRoute(next);setData(null);}}
 async function discover(){if(!hasKey){openKey();return;}const id=++requestId.current;abort.current?.abort();abort.current=new AbortController();setBusy(true);setError('');setData(null);setPhase('Searching the live web…');const timer=setTimeout(()=>setPhase('Reading menus and official pages…'),4500);try{const res=await fetch('/api/discover',{method:'POST',headers:requestHeaders(),body:JSON.stringify({species:fish.id,route,location,country}),signal:abort.current.signal});const value=await res.json();if(!res.ok)throw new Error(value.error);if(id===requestId.current)setData(value);}catch(e){if(id===requestId.current&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Something went wrong.');}finally{clearTimeout(timer);if(id===requestId.current)setBusy(false);}}
 async function inspect(item:Result){if(!hasKey){openKey();return;}const controller=new AbortController();keyRequests.current.add(controller);const stateKey=fish.id+item.url;setAgents(s=>({...s,[stateKey]:{busy:true,progress:'Opening the venue’s website…'}}));try{const res=await fetch('/api/inspect',{method:'POST',headers:requestHeaders(),body:JSON.stringify({token:item.token,species:fish.id,route,location:data?.location||location}),signal:controller.signal});if(!res.ok){const e=await res.json();throw new Error(e.error);}const reader=res.body!.getReader();const decoder=new TextDecoder();let buffer='',complete=false;while(true){const {done,value}=await reader.read();if(controller.signal.aborted)return;if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;try{const event=JSON.parse(line.slice(5).trim());if(event.type==='COMPLETE'){if(event.status&&event.status!=='COMPLETED')throw new Error(event.error?.message||'The agent could not finish this check.');let result=event.result||event.resultJson;if(typeof result==='string'){try{result=JSON.parse(result.replace(/^```json\s*|```$/g,''));}catch{result={summary:result};}}if(!result)result={summary:'The agent finished without structured evidence. Check the original source.'};setAgents(s=>({...s,[stateKey]:{busy:false,progress:'Check complete',result}}));complete=true;}else if(event.type==='ERROR'){throw new Error(event.message||'Agent error.');}else if(event.purpose||event.message){setAgents(s=>({...s,[stateKey]:{busy:true,progress:String(event.purpose||event.message).slice(0,180)}}));}}catch(e){if(e instanceof SyntaxError)continue;throw e;}}}if(!complete)throw new Error('The connection ended before a completed result. The agent may still be running; avoid immediately starting another.');}catch(e){if(controller.signal.aborted)return;setAgents(s=>({...s,[stateKey]:{busy:false,progress:'',error:e instanceof Error?e.message:'Could not check this page.'}}));}finally{keyRequests.current.delete(controller);}}
 async function recipes(){if(!hasKey){openKey();return;}const controller=new AbortController();keyRequests.current.add(controller);setRecipeBusy(true);setRecipeError('');try{const res=await fetch('/api/recipes',{method:'POST',headers:requestHeaders(),body:JSON.stringify({species:fish.id}),signal:controller.signal});const v=await res.json();if(!res.ok)throw new Error(v.error);if(!controller.signal.aborted)setRecipe(v.results);}catch(e){if(controller.signal.aborted)return;setRecipeError(e instanceof Error?e.message:'Recipe search failed.');}finally{keyRequests.current.delete(controller);if(!controller.signal.aborted)setRecipeBusy(false);}}

const index=creatures.findIndex(c=>c.id===fish.id),next=creatures[(index+1)%creatures.length];const details=routeDetails[route];const lifeArt:Record<string,[string,number][]>= {salmon:[['lifecycle-fish',0],['lifecycle-fish',1],['lifecycle-fish',2]],clownfish:[['lifecycle-fish',5],['lifecycle-fish',4],['lifecycle-fish',3]],seahorse:[['lifecycle-fish',6],['lifecycle-fish',6],['lifecycle-fish',7]],prawn:[['lifecycle-invertebrates',0],['lifecycle-invertebrates',1],['lifecycle-invertebrates',2]],crab:[['lifecycle-invertebrates',0],['lifecycle-invertebrates',3],['lifecycle-invertebrates',4]],octopus:[['lifecycle-invertebrates',6],['lifecycle-invertebrates',7],['seafood-atlas-shellfish',7]],squid:[['lifecycle-invertebrates',6],['lifecycle-invertebrates',8],['lifecycle-invertebrates',8]]};
return <div className="app-shell detail-shell" style={{backgroundImage:`linear-gradient(90deg,#04192338,#04192355),url('/art/habitat-${fish.habitat}.png')`}}>
<header className="site-header"><Link className="brand" href="/"><Specimen fish={creatures[4]} className="brand-fish"/><span className="fishies-wordmark">FISHIES<span className="pixel-spark">✦</span></span></Link><Link className="back-catalogue" href="/"><ArrowLeft size={15}/> All creatures</Link><TinyFishKeyButton/><Link className="next-creature" href={`/creature/${next.id}`}>{next.name}<ArrowRight size={15}/></Link></header>
<div className="detail-toolbar"><div className="detail-identity"><span className="eyebrow">SPECIMEN {String(index+1).padStart(2,'0')}</span><span>{fish.name}</span></div><nav className="view-tabs" aria-label="Explore this creature"><button className={view==='about'?'active':''} onClick={()=>switchView('about')}><Globe2 size={16}/> About</button>{(['see','eat','buy'] as Route[]).filter(r=>fish.routes.includes(r)).map(r=>{const Icon=routeDetails[r].icon;return <button key={r} className={view===r?'active':''} onClick={()=>switchView(r)}><Icon size={16}/>{r==='see'?'See it':r==='eat'?'Eat it':'Buy & cook'}</button>;})}</nav></div>
<main className="detail-workspace">
<section className={`world-stage ${view!=='about'?'venue-stage':''}`} style={{backgroundImage:`url('/art/${view==='about'?'habitat-'+fish.habitat:'destination-'+(view==='buy'&&cookTab==='recipes'?'kitchen':details.scene)}.png')`}}>
<div className="world-stage-shade"/>{view!=='about'&&<div className="destination-overlay" style={{backgroundImage:`url('/art/destination-${view==='buy'&&cookTab==='recipes'?'kitchen':details.scene}.png')`}}/>}<div className="stage-heading"><span className="eyebrow light">{view==='about'?fish.region:view==='see'?'AQUARIUMS & EXHIBITS':view==='eat'?'RESTAURANTS':'SHOPS & RECIPES'}</span><h1>{fish.name}</h1><p>{fish.latin}</p></div>
{view==='about'?<><div className="stage-fish swimmer"><Specimen fish={fish}/></div><div className="stage-globe"><Globe coords={fish.coords}/><button className="expand-globe" onClick={()=>setGlobeOpen(true)}><Maximize2 size={13}/> Explore the globe</button></div><div className="stage-footnote"><span><i/> {fish.water}</span><small>Illustrative habitat markers</small></div></>:<><div className="venue-specimen"><Specimen fish={fish}/></div><button className="return-about" onClick={()=>switchView('about')}><Globe2 size={16}/> Back to its world</button><div className="venue-stage-caption">{view==='see'?'Find a place to see it.':view==='eat'?'Check the menu.':'Choose what to cook.'}</div></>}
</section>
<section className="detail-panel">
{view==='about'?<><div className="panel-tabs"><button className={aboutTab==='overview'?'active':''} onClick={()=>setAboutTab('overview')}>Overview</button><button className={aboutTab==='life'?'active':''} onClick={()=>setAboutTab('life')}>Lifecycle</button></div><div className="panel-scroll">{aboutTab==='overview'?<><span className="eyebrow">{fish.family.toUpperCase()}</span><div className="hud-name"><h2>{fish.name}</h2><p>{fish.latin}</p></div><p className="detail-description">{fish.description}</p><div className="field-fact"><span className="eyebrow">DID YOU KNOW?</span><p>{fish.tagline}</p><a href={fish.factSource||fish.source} target="_blank" rel="noreferrer">Read the source <ArrowUpRight size={12}/></a></div><dl className="species-facts"><div><dt>WHERE IT LIVES</dt><dd>{fish.region}</dd></div><div><dt>WHAT IT EATS</dt><dd>{fish.diet}</dd></div><div><dt>DISTINCTIVE FEATURE</dt><dd>{fish.trait}</dd></div></dl>{fish.routes.length>0?<div className="about-actions">{fish.routes.map(r=>{const Icon=routeDetails[r].icon;return <button key={r} onClick={()=>switchView(r)}><Icon size={17}/>{r==='see'?'See it':r==='eat'?'Eat it':'Buy & cook'}<ArrowRight size={14}/></button>;})}</div>:<p className="quiet-note">Explore this deep-sea animal through the researchers who study it. This guide has no visitor or food listings for it.</p>}</>:<><span className="eyebrow">FROM DEVELOPMENT TO ADULTHOOD</span><h2 className="hud-title">Lifecycle</h2><div className="compact-lifecycle">{fish.stages.map((title,i)=><article key={title}><span className="stage-number">0{i+1}</span><div><h3>{title}</h3><p>{fish.life[i]}</p></div>{i===3?<Specimen fish={fish}/>:lifeArt[fish.id]?.[i]&&!(fish.id==='crab'&&i===0)&&!(fish.id==='squid'&&i===0)?<Sprite atlas={lifeArt[fish.id][i][0]} cell={lifeArt[fish.id][i][1]}/>:null}</article>)}</div><p className="quiet-note">Stages are simplified. Development and timing vary between species and populations.</p><a className="text-link" href={fish.source} target="_blank" rel="noreferrer">Natural history source <ArrowUpRight size={14}/></a></>}</div></>:<><div className="panel-topline"><span className="eyebrow">{fish.name.toUpperCase()}</span><span className="tinyfish-mark"><i className="live-dot"/> LIVE · TINYFISH</span></div>{view==='buy'&&<div className="panel-tabs"><button className={cookTab==='shops'?'active':''} onClick={()=>setCookTab('shops')}>Buy it</button><button className={cookTab==='recipes'?'active':''} onClick={()=>setCookTab('recipes')}>Cook it</button></div>}<div className="panel-scroll"><TinyFishKeyNotice/>
{view==='buy'&&cookTab==='recipes'?<><h2 className="hud-title">Cook {fish.menu}</h2><div className="recipe-plate"><Sprite atlas={fish.shellfish?'dishes-shellfish':'dishes-fish'} cell={fish.dish||0}/><span>SERVING SUGGESTION</span></div><p className="detail-description">Find recipes with preparation steps, ingredients and cooking instructions.</p><button className="dark-button" onClick={recipes} disabled={recipeBusy}>{recipeBusy?<Loader2 className="spin" size={16}/>:<BookOpen size={16}/>} {recipeBusy?'Searching recipes…':hasKey?'Find recipes':'Add key to find recipes'}<ArrowRight size={16}/></button><div className="compact-kitchen">{[{atlas:'props-ingredients',cell:0,name:'Butter'},{atlas:'props-ingredients',cell:1,name:'Lemon'},{atlas:'props-ingredients',cell:3,name:'Herbs'},{atlas:'props-cookware',cell:0,name:'Pan'}].map(p=><div key={p.name}><Sprite {...p}/><span>{p.name}</span></div>)}</div>{recipeError&&<p role="alert" className="warning-note">{recipeError}</p>}<div className="recipe-list">{recipe.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer"><BookOpen size={18}/><div><h4>{r.title}</h4><p>{r.snippet}</p></div><ArrowUpRight size={15}/></a>)}</div><p className="quiet-note">Follow the linked recipe’s preparation and food-safety guidance. Ask the fishmonger about origin and production method.</p></>:<><h2>{details.title.replace(/\.$/,'')}</h2><p className="detail-description">{details.subtitle}</p><form className="compact-search" onSubmit={e=>{e.preventDefault();discover();}}><label htmlFor="location">LOCATION</label><div className="location-input"><MapPin size={17}/><input id="location" required minLength={2} maxLength={120} placeholder="City, neighbourhood or postcode" value={location} onChange={e=>setLocation(e.target.value)}/></div><select aria-label="Country" value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><button className="dark-button" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Search size={16}/>} {busy?'Searching…':hasKey?details.title:'Add key to search'}<ArrowRight size={16}/></button></form><p className="form-note">Results link to current venue pages. A menu name may refer to more than one species.</p>{error&&<div className="error-box" role="alert"><Info size={18}/><div><strong>Search could not finish.</strong><p>{error}</p></div><button onClick={discover}><RefreshCw size={15}/>Retry</button></div>}{busy&&<div className="compact-loading" aria-live="polite"><Specimen fish={fish}/><p>{phase}</p></div>}
 {data&&<div className="live-results"><div className="results-heading"><div><span className="eyebrow">THE LATEST FROM {data.location.toUpperCase()}</span><h3>{data.results.length?`${data.results.length} search results.`:'No matches surfaced this time.'}</h3></div><span className="checked-time"><Check size={14}/> Checked {new Date(data.checkedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})} · {data.endpoints.join(' + ')}</span></div>{data.warning&&<p className="warning-note">{data.warning}</p>}<div className="result-grid">{data.results.map((r,i)=>{const agent=agents[fish.id+r.url];return <article className="result-card" key={r.url}><div className="result-top"><span className="result-number">0{i+1}</span><span className={`evidence-tag ${r.mention?'positive':''}`}>{r.mention?'Named on the page':r.checked?'Page read · match unconfirmed':'Search lead · not page-verified'}</span></div><a href={r.url} target="_blank" rel="noreferrer"><h4>{r.title}<ArrowUpRight size={18}/></h4></a><p>{r.snippet}</p>{r.excerpts.length>0&&<blockquote>{r.excerpts[0]}</blockquote>}<div className="result-domain">{new URL(r.url).hostname.replace('www.','')}{r.exactSpecies&&<span> · Scientific name found</span>}</div><button className="agent-button" disabled={agent?.busy} onClick={()=>inspect(r)}>{agent?.busy?<Loader2 className="spin" size={15}/>:<Compass size={15}/>} {agent?.busy?'Checking the details…':agent?.result?'Check again with TinyFish Agent':'Ask TinyFish to check the details'}<ChevronRight size={15}/></button>{agent?.busy&&<p className="agent-progress" aria-live="polite">{agent.progress}</p>}{agent?.error&&<p className="warning-note" role="alert">{agent.error}</p>}{agent?.result&&<div className="agent-result"><span className="eyebrow">AGENT FIELD NOTES</span>{Object.entries(agent.result).map(([k,v])=>v!==null&&v!==undefined&&<div key={k}><strong>{k.replace(/([A-Z])/g,' $1')}</strong><span>{Array.isArray(v)?v.map(String).join(' · '):typeof v==='object'?JSON.stringify(v):String(v)}</span></div>)}</div>}</article>;})}</div><p className="quiet-note">A live page check confirms what the website says, not real-time stock, an available table or a guaranteed animal sighting.</p></div>}
</>}
</div></>}
</section></main>
{globeOpen&&<div className="globe-overlay" role="dialog" aria-modal="true" aria-label="Habitat globe"><button className="close-globe" aria-label="Close globe" onClick={()=>setGlobeOpen(false)}><X/></button><div><span className="eyebrow">{fish.name.toUpperCase()}</span><h2>{fish.region}</h2><Globe coords={fish.coords}/><p>Illustrative habitat regions, not an exact distribution map.</p><a className="text-link" href={fish.source} target="_blank" rel="noreferrer">Read about its range <ArrowUpRight size={14}/></a></div></div>}
</div>;
}
