 'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Search,X} from 'lucide-react';
import {creatures} from '@/lib/catalogue';
import {Specimen} from './specimen';
import RequestCreature from './request-creature';
import {TinyFishKeyButton} from './tinyfish-key';
export default function Catalogue(){
 const [search,setSearch]=useState(''),[family,setFamily]=useState('All');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{function focus(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();input.current?.focus();}}window.addEventListener('keydown',focus);return()=>window.removeEventListener('keydown',focus);},[]);
 const terms=search.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const filtered=creatures.filter(c=>(family==='All'||c.family===family)&&terms.every(w=>`${c.name} ${c.latin} ${c.keywords}`.toLowerCase().includes(w)));
 return <div className="app-shell catalogue-shell"><header className="site-header"><Link className="brand" href="/"><Specimen fish={creatures[4]} className="brand-fish"/><span className="fishies-wordmark">FISHIES<span className="pixel-spark">✦</span></span></Link><span className="header-caption">AN ILLUSTRATED FIELD GUIDE</span><TinyFishKeyButton/><Link className="art-room-link" href="/studio">The art room <ArrowUpRight size={14}/></Link></header><main className="catalogue-main"><section className="catalogue-intro search-first"><h1 className="sr-only">Search the creature collection</h1><div className="catalogue-search-area"><div className="catalogue-search primary-search"><Search size={25}/><input ref={input} aria-label="Name a fish or describe it" placeholder="Name a fish or describe it" value={search} onChange={e=>setSearch(e.target.value)}/>{search?<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={20}/></button>:<kbd>⌘ K</kbd>}</div><div className="search-meta"><span>Try “orange white stripes”, “eight arms” or “lobster”</span><span aria-live="polite">{search||family!=='All'?`${filtered.length} of ${creatures.length}`:creatures.length} creatures</span></div><div className="family-filters">{['All','Fish','Reef life','Shellfish','Cephalopods','Deep sea'].map(f=><button key={f} onClick={()=>setFamily(f)} className={family===f?'active':''}>{f}</button>)}</div></div></section><section className="collection-scroll" aria-label="Creature collection"><div className="creature-grid">{filtered.map((c,i)=><Link key={c.id} className={`creature-card creature-${c.habitat}`} href={`/creature/${c.id}`}><div className="creature-card-scene" style={{backgroundImage:`url('/art/habitat-${c.habitat}.png')`}}/><span className="card-number">{String(creatures.indexOf(c)+1).padStart(2,'0')}</span><Specimen fish={c}/><div className="card-caption"><span className="eyebrow">{c.family}</span><h2>{c.name}</h2><p>{c.latin}</p></div><span className="card-arrow"><ArrowRight size={18}/></span></Link>)}</div>{filtered.length===0&&<p className="empty-state">No creatures match. Try another name or a shorter description.</p>}<div className="catalogue-end"><RequestCreature/><p>Illustrations are stylised. This catalogue matches names and keywords, rather than identifying animals from photographs.</p></div></section></main></div>;
}
