import {createHmac,timingSafeEqual} from 'node:crypto';
export class TinyFishKeyError extends Error {}
// Every caller supplies their own key. Never fall back to a hosting environment key.
export function apiKey(req:Request){const key=req.headers.get('X-TinyFish-Key')?.trim();if(!key||!/^[\x21-\x7E]{16,512}$/.test(key))throw new TinyFishKeyError('Enter your own TinyFish API key to use live search.');return key;}
export function apiError(error:unknown,fallback:string){return Response.json({error:error instanceof Error?error.message:fallback},{status:error instanceof TinyFishKeyError?401:503,headers:{'Cache-Control':'no-store'}});}
export function signedUrl(url:string,key:string){const expiry=Date.now()+3600000;const body=Buffer.from(JSON.stringify({url,expiry})).toString('base64url');return body+'.'+createHmac('sha256',key).update(body).digest('hex');}
export function verifyToken(token:string,key:string){const [body,mac]=token.split('.');const expected=createHmac('sha256',key).update(body||'').digest('hex');if(!mac||mac.length!==expected.length||!timingSafeEqual(Buffer.from(mac),Buffer.from(expected)))throw new Error('Please run a fresh search before checking this page.');const data=JSON.parse(Buffer.from(body,'base64url').toString());if(data.expiry<Date.now())throw new Error('This result expired. Please search again.');return data.url as string;}
export function publicUrl(value:string){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!/^(localhost|127\.|10\.|192\.168\.|169\.254\.|0\.|\[|172\.(1[6-9]|2\d|3[01])\.)/i.test(u.hostname)&&u.hostname.includes('.');}catch{return false;}}
export function safeError(status:number){return status===401?'TinyFish could not accept this API key. Check the key you entered.':status===402?'This TinyFish endpoint needs account access or credits.':status===429?'TinyFish is busy. Give it a moment and try again.':`TinyFish returned an error (${status}). Please try again.`;}
const counts=new Map<string,{count:number;reset:number}>();
export function checkRequest(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('This request must come from Fishies.');const id=req.headers.get('x-forwarded-for')?.split(',')[0]||'local';let bucket=counts.get(id);if(!bucket||bucket.reset<Date.now())bucket={count:0,reset:Date.now()+60000};bucket.count++;counts.set(id,bucket);if(bucket.count>12)throw new Error('Too many requests. Please wait a minute.');}
